### ISSUE TITLE
GitLab Issue forwarding

### ISSUE THREAD

**Issue by Freymaurer** [Freymaurer/nfdi-helpdesk#10]
https://git.nfdi4plants.org/martinkuhl/SampleARC_Proteomics

https://git.nfdi4plants.org/brilator/samplearc_rnaseq

https://git.nfdi4plants.org/brilator/samplearc_metabolomics

Forward issues to SampleARC Channel (ARCS)

**Comment by Brilator** [comment]
Outdated, since we wanted to move away from ARCs labelled "Sample ARC".
